## Obsługa Notebook'a

Obsługa notatnika jest wyjątkowo prosta. Najważniejsze informacje:
* Pojedynczą komórkę wykonujemy kombinacją klawiszy Shift+Enter.
* Jeżeli chcemy uruchomić wszystkie komórki lub np. wszystkie poniżej obecnei aktywnej, powyżej Wybieramy Cell > i stosowną opcję Run.
* Ikona kwadratu zatrzyma obecnie wykonywaną operację.
* Ikona "+" dodaje nową pustą komórkę pod obecnie wybraną.
* Kombinacja klawiszy Ctrl+/ słuzy do komentowania linii.
* Jeżeli chcemy zmienić typ komórki z kodu na tekst/opis z rozwijanej listy na powyższym pasku wybieramy "Markdown" zamiast "Code".
* Kernel (dany notatnik) możemy uruchomić ponownie wybierając Kernel > Restart powyżej lub ikonę zakręconej strzałki. Ponowne uruchomienie notatnika spowoduje utratę wszystkich wyników.
* Co jakiś czas notatnik zapisuje się automatycznie. Niemniej warto w kluczowych momentach korzystać z ręcznego zapisu (Ctrl+S).

W celu przetestowania instalacji możemy uruchomić wszystkie poniższe komórki.

In [ ]:
#W Pythonie biblioteki ładujemy poleceniem "import". Przy importowaniu bibliotek możemy im zdefiniować alias/nazwę używając "as".
# Pandas i Numpy to bardzo często wykorzystywane biblioteki.
# Skrócenie ich nazwy oszczędzi nam trochę pisania.
# Skróty "np" i "pd" są powszechnie wykorzystywane.
import numpy as np
import pandas as pd

## Test Numpy
Sprawdźmy czy działa Numpy. Wykonajmy kilka podstawowych poleceń i sprawdźmy czy uzyskujemy oczekiwane rezultaty.

In [ ]:
print (np.__version__)
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(type(a))
print("Suma macierzy to: ", a.sum())


Wykonanie powyższych poleceń powinno dać następujący wynik (z dokładnością do wersji pakietu):
```
1.11.2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
<class 'numpy.ndarray'>
Suma macierzy to:  66
```

## Test Pandas
Sprawdźmy czy działa Pandas. W tym celu wykonajmy kilka pierwszych poleceń z tutoriala:
http://pandas.pydata.org/pandas-docs/stable/10min.html

In [ ]:
print (pd.__version__)
s = pd.Series([1,3,5,np.nan,6,8])
print(s)
print("Suma serii to: ", s.sum())
dates = pd.date_range('20130101', periods=6)
print(dates)
df2 = pd.DataFrame({ 'A' : 1., 'B' : pd.Timestamp('20130102'), 'C' : pd.Series(1,index=list(range(4)),dtype='float32'), 'D' : np.array([3] * 4,dtype='int32'), 'E' : pd.Categorical(["test","train","test","train"]), 'F' : 'foo' })
print(df2)
print(df2.dtypes)

Wykonanie powyższych poleceń powinno dać następujący wynik (z dokładnością do wersji pakietu):
```
0.19.2
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
Suma serii to:  23.0
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
```